services:
  resume-api:
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    environment:
      RESUME_API_KEY: "JJ5wgXr8laxo1EpdQ7DgGdMHrUDKLEme4canEZ6bGp0"
      CORS_ORIGINS: "*"
      MAX_UPLOAD_BYTES: "10485760"
      API_VERSION: "1.0.0"
    volumes:
      - ./models:/app/models:ro
